---
- name: Setup server for interview
  hosts: all
  become: yes  
  tasks:
    - name: 1. Create hero user
      user:
        name: hero
        shell: /bin/bash
        create_home: yes

    - name: 2. Create superhero user
      user:
        name: superhero
        shell: /bin/bash
        create_home: yes

    - name: 3. Set password for hero
      user:
        name: hero
        password: "{{ 'supersafepassword' | password_hash('sha512') }}"

    - name: 4. Set password for superhero
      user:
        name: superhero
        password: "{{ 'superheropassword' | password_hash('sha512') }}"

    - name: 5. Add superhero to sudo group
      user:
        name: superhero
        groups: sudo
        append: yes

    - name: 6. Ensure /.app directory exists
      file:
        path: /.app
        state: directory
        mode: '0755'
    - name: 7. Install packages
      apt:
        name:
          - git
          - nginx
          - python3-pip
          - python3-venv  
          - cowsay
          - tmux
          - auditd
          - audispd-plugins
          - vim
          - net-tools
        state: present
        update_cache: yes

    - name: 8. Clone interview repo
      git:
        repo: https://github.com/abulkatim/interview.git
        dest: /.app/interview
        clone: yes
        update: yes

    - name: 9. Install Flask globally
      pip:
        name: flask
        executable: pip3

    - name: 10. Create venv in /.app
      command: /usr/bin/python3 -m venv /.app/.venv

    - name: 11. Install Python packages in venv
      pip:
        requirements: /.app/interview/requirements.txt
        virtualenv: /.app/.venv

    - name: 12. Add /usr/games to PATH 
      lineinfile:
        path: /etc/environment
        line: "PATH={{ lookup('env', 'PATH') }}:/usr/games"
        state: present
        create: yes

    - name: 13. Copy strange box
      copy:
        src: /.app/interview/strange_box.tar.gz  
        dest: /home/hero/strange_box.tar.gz
        mode: '0644'
        remote_src: yes

    - name: 14. Copy HTML
      copy:
        src: "/.app/interview/app/html/"
        dest: "/var/www/html/"
        mode: '0755'
        remote_src: yes

    - name: 15. Cp Flask conf
      copy:
        src: "/.app/interview/flask_app"
        dest: /etc/nginx/sites-available/flask_app
        mode: '0644'
        remote_src: yes

    - name: 16.Symlink flask_app
      file:
        src: /etc/nginx/sites-available/flask_app
        dest: /etc/nginx/sites-enabled/flask_app
        state: link

    - name: 17. Remove default Nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: 18. Check perms for broken_backend
      file: 
        path: /.app/interview/app/broken_backend.py
        owner: root
        group: root
        mode: '0755'
        state: file
        follow: yes

    - name: 19. Run broken_backend.py in the background inside virtualenv
      shell: "/.app/.venv/bin/python3 /.app/interview/app/broken_backend.py > /tmp/broken_backend.log 2>&1 &"
      become: yes

    - name: 20. Set up interview-backend 
      copy:
        src: /.app/interview/interview-backend.service
        dest: /etc/systemd/system/interview-backend.service
        mode: '0644'
        remote_src: yes

    - name: 21. Reload systemd
      systemd:
        daemon_reload: yes

    - name: 22. Start interview-backend 
      systemd:
        name: interview-backend.service
        state: started
        enabled: yes
      ignore_errors: yes

    - name: 23. Restart Nginx 
      systemd:
        name: nginx
        state: restarted
      ignore_errors: yes  

    - name: 24. Tmux auto-start hero 
      lineinfile:
        path: /home/hero/.bashrc
        line: |
          if [[ -z "$TMUX" ]] && [[ -n "$SSH_CONNECTION" ]]; then
              tmux new-session -A -s interview
          fi
        create: yes
        state: present

    - name: 25. Tmux auto-start superhero 
      lineinfile:
        path: /home/superhero/.bashrc
        line: |
          if [[ -z "$TMUX" ]] && [[ -n "$SSH_CONNECTION" ]]; then
              tmux new-session -A -s interview
          fi
        create: yes
        state: present

    - name: 26. SCheck perms .bashrc hero
      file:
        path: /home/hero/.bashrc
        owner: hero
        group: hero
        mode: '0644'

    - name: 27. Check perms .bashrc superhero
      file:
        path: /home/superhero/.bashrc
        owner: superhero
        group: superhero
        mode: '0644'

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
